version: '3.8'

services:
  link-desk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link-desk
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - GIN_MODE=release
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET:-change_this_to_a_secure_secret_in_production}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
      - DB_PATH=/app/data/linkdesk.db
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8080}
    restart: unless-stopped 